# Generated by Django 2.2 on 2018-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181019_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=32),
        ),
    ]
