# Generated by Django 2.1.1 on 2018-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalTrends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostPopularVehicle', models.CharField(max_length=50)),
                ('mostPopularType', models.CharField(max_length=50)),
                ('mostPopularMonth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTrends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.CharField(max_length=250)),
                ('storeProductivity', models.CharField(max_length=50)),
                ('mostProductiveMonth', models.CharField(max_length=50)),
                ('mostRentedVehicle', models.CharField(max_length=50)),
                ('mostPickupOrReturn', models.CharField(max_length=10)),
            ],
        ),
    ]
